### ISSUE TITLE
小程序中如何取消边界判断功能

### ISSUE THREAD

**Issue by dijiagui** [newbieYoung/Simple-Crop#12]
想要禁用边界判断的功能，如何配置

**Comment by newbieYoung** [comment]
@dijiagui 出于什么考虑需要禁用边界判断呢？

**Comment by dijiagui** [comment]
比如说我有一个4:3的图片a，我的裁剪框是16:9，我的目标是生成一张16:9的图片。
当我将这张图片a加载的时候，目前我无法将整张图片放入裁剪框的，只能从上截取一部分,但是其实我想保留图片完整信息。
@newbieYoung

**Comment by newbieYoung** [comment]
@dijiagui  那空出的部分用什么填充呢？

**Comment by dijiagui** [comment]
@newbieYoung 我的一个想法是所见即所得，用当前背景颜色，不知道是否可以？

**Comment by newbieYoung** [comment]
@dijiagui 也可以但是得排后了

**Comment by dijiagui** [comment]
@newbieYoung  好的，谢谢
