### ISSUE TITLE
QQ小程序出错

### ISSUE THREAD

**Issue by yonglin-z** [newbieYoung/Simple-Crop#13]
非常不错的实现，微信小程序下完美运行，但QQ小程序运行错误。对canvas不太熟，能帮忙修改兼容下QQ小程序不？

**Comment by yonglin-z** [comment]
this.$cropContent = this.createSelectorQuery().select('#' + S_ID + ' .crop-content');
      total_count++;
      this.$cropContent.node().exec(function (res) {
        self.$cropContent = res[0].node;
        self.cropContentCtx = self.$cropContent.getContext('2d');
        call_count++;
        callback();
      });

这一段代码报错：this.$cropContent.node is not a function;

**Comment by newbieYoung** [comment]
@yonglin-z  本周末得处理几个 issue，处理完再看吧，qq小程序是直接拿的微信的代码，如果有异常，应该是 qq 小程序抄的微信小程序版本不兼容。

**Comment by yonglin-z** [comment]
QQ小程序不支持通过.node()函数获得canvas实例
