### ISSUE TITLE
在微信小程序上加载10m的图片时貌似不行

### ISSUE THREAD

**Issue by CHIMtao** [newbieYoung/Simple-Crop#18]
加载时间很长，而且也卡，最后在裁剪页面啥都没有，用不了

**Comment by newbieYoung** [comment]
图片太大了，裁剪之前压缩一下。

**Comment by CHIMtao** [comment]
有试了在用之前用其他框架压缩成几百Kb，连着压缩完就直接传裁剪上，然后有时候就会在裁剪那里加载一会儿，然后甚至整个微信都崩溃了，平台：ios 13.3

**Comment by newbieYoung** [comment]
压缩完的图片给我试下？或者上传个代码片段？

**Comment by fafayzf** [comment]
我这边也有这个问题，前提是从相册选择原图，初始化会空白

**Comment by newbieYoung** [comment]
图片的宽度、高度、大小有限制，建议在 wx.chooseImage 选择图片时 sizeType 设置为 compressed。
