### ISSUE TITLE
将img的src改为动态上传的，然后裁剪出来的图片位置不对

### ISSUE THREAD

**Issue by yangdongMC** [newbieYoung/Simple-Crop#2]
我是将传入的src 通过input的file 类型进行上传，然后转换成base64在img 中进行显示，移动、旋转功能都没有问题，但是最后裁剪出来的跟裁剪前放到可视区域中的不一样；
还有个小问题是rotateSlider设为false 时，再点击旋转会报错。

**Comment by newbieYoung** [comment]
ios 系统拍照方向角问题，已修复。
