### ISSUE TITLE
裁剪的图片变模糊

### ISSUE THREAD

**Issue by fafayzf** [newbieYoung/Simple-Crop#21]
vx小程序中，传入远程的图片url后，初始化后一直到transformCoordinates这个方法下的image都是清晰的，裁剪后变得很模糊，后面我在transformCoordinates这个方法下，把调用wx.canvasToTempFilePath的destWidth和destHeight都放大到wx.getSystemInfoSync().pixelRatio倍数，才好那么一点点，但是还是模糊，求解，基础库为2.11.1，机型安卓和iOS都模糊

**Comment by newbieYoung** [comment]
@fafayzf 搞个代码片段看看？项目里边的例子也会模糊吗？

**Comment by fafayzf** [comment]
> @fafayzf 搞个代码片段看看？项目里边的例子也会模糊吗？
我把同样的代码片段做demo测试，图片就不会模糊，要是发你也是不会模糊的，放在项目里就有问题，https://developers.weixin.qq.com/community/develop/article/doc/0002c66c030410cfc28a15ff25b013，这里发的图片示例，是放在项目里的，可以看一下，不知道哪个环节出错了

**Comment by fafayzf** [comment]
> @fafayzf 搞个代码片段看看？项目里边的例子也会模糊吗？
[https://developers.weixin.qq.com/s/7WnSSlm27oiX]

**Comment by fafayzf** [comment]
> @fafayzf 搞个代码片段看看？项目里边的例子也会模糊吗？

[这里是代码片段](https://developers.weixin.qq.com/s/7WnSSlm27oiX)，这个片段是没问题，但是这个是从项目里拷贝出来的，同样的代码，我放在项目里跑就会模糊，[这里是项目里代码片段的图片示例，点击可以查看](https://developers.weixin.qq.com/community/develop/article/doc/0002c66c030410cfc28a15ff25b013)，不清楚是哪里出了问题
