### ISSUE TITLE
IOS微信小程序不显示图片

### ISSUE THREAD

**Issue by FJune** [newbieYoung/Simple-Crop#25]
我微信版本是 7.0.3 ，从相册选择完图片上传上去之后不显示图片，目前是必现

**Comment by newbieYoung** [comment]
@FJune

**Comment by wkiwi** [comment]
> 我微信版本是 7.0.3 ，从相册选择完图片上传上去之后不显示图片，目前是必现

这个小程序使用的是canvas2d 版本要求比较高 2.9起才能使用

**Comment by newbieYoung** [comment]
你弄个代码片段，我看下吧



---原始邮件---
发件人: "不止是前端"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 下午3:25
收件人: "newbieYoung/Simple-Crop"<Simple-Crop@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Young"<657851574@qq.com&gt;;
主题: Re: [newbieYoung/Simple-Crop] IOS微信小程序不显示图片 (#25)




  
我微信版本是 7.0.3 ，从相册选择完图片上传上去之后不显示图片，目前是必现
  
这个小程序使用的是canvas2d 版本要求比较高 2.9起才能使用

**Comment by KingCheni** [comment]
ios确实不显示，我这边也出现了

**Comment by newbieYoung** [comment]
@KingCheni  ios 版本多少？微信版本多少？

**Comment by KingCheni** [comment]
> @KingCheni ios 版本多少？微信版本多少？

iPhone 7 Plus 13.6 微信7.0.15

**Comment by KingCheni** [comment]
> @KingCheni ios 版本多少？微信版本多少？

等会。我发现问题了，用image组件可以查看到临时图片，但是用background-image样式就不显示，应该是这个问题。不过在安卓端，该样式也可以显示图片
