### ISSUE TITLE
页面一开始加载图片，图片会被压缩变形这个怎么解决

### ISSUE THREAD

**Issue by boosver** [newbieYoung/Simple-Crop#30]
页面一开始加载图片，图片会被压缩变形这个怎么解决
![image](https://user-images.githubusercontent.com/39890885/103079577-12468f80-460f-11eb-917c-b16cd9bcae59.png)

**Comment by boosver** [comment]
配置参数和代码都是根据提供的demo使用的只是我的加载图片方式不是用上传，而是直接加载网络图

**Comment by newbieYoung** [comment]
@boosver 图片链接发给我试试？

**Comment by boosver** [comment]
解决了我自己的问题感谢感谢
