### ISSUE TITLE
是否可以支持自由描边？

### ISSUE THREAD

**Issue by yafeisong** [newbieYoung/Simple-Crop#36]
现在裁剪区域固定成了矩形，虽然支持自由旋转，但是对于有些因拍摄角度而导致的两边长度不一样的图片，不能进行精确的裁剪，是否可以支持自由描边，类似于PS中的描边抠图的效果?

**Comment by newbieYoung** [comment]
两边长度不一致是啥意思，2d 操作矩形足够了吧，没太理解

**Comment by yafeisong** [comment]
就是有些图片在拍摄时，可能因为拍摄角度的问题，有一定的倾斜，这样，在用 Simple-Crop 进行裁剪时，因为 Simple-Crop 目前只能用方方正正的矩形来裁剪，对于这种图片，不能很精确的按照边线进行裁剪。如果有可以自由绘制裁剪区域，那就更加完善了。
类似于这样的图片：
![微信图片_20210915164632](https://user-images.githubusercontent.com/18110010/133540531-d66717ee-8f5b-4b20-acba-7264425a7966.jpg)

**Comment by newbieYoung** [comment]
首先图片都是矩形的，其次这种情况你可以用矩形裁剪，然后使用边框识别算法去掉其它部分；
这里没必要让用户手动描边去做。
