### ISSUE TITLE
裁剪图片模糊

### ISSUE THREAD

**Issue by Wangsenshuai** [newbieYoung/Simple-Crop#4]
请问裁剪图片模糊怎么解决

**Comment by newbieYoung** [comment]
小程序吗？

**Comment by newbieYoung** [comment]
微信小程序 demo 中选择裁剪图片那里被我限制了不能选择原图，主要是因为原图太大，微信小程序在某些机型上会crash；你在实际使用时可以去掉这个限制，SimpleCrop 组件本身并不存在清晰度损失。

**Comment by Wangsenshuai** [comment]
是的，我看了源码猜测是图片没有压缩，并且会导致打开失败。现在用了chooseImage选择压缩，暂时没有原图的要求。多谢
