### ISSUE TITLE
小图裁剪尺寸不正确问题

### ISSUE THREAD

**Issue by zhu644179766** [newbieYoung/Simple-Crop#5]
913行，cropWidth / contentWidth > cropHeight > contentHeight，是不是写错了，应该是cropWidth / contentWidth > cropHeight / contentHeight

**Comment by newbieYoung** [comment]
是的，笔误，谢谢提醒

**Comment by newbieYoung** [comment]
npm 4.0.7 已修复，微信小程序 demo 已提交审核，审核通过第一时间发布。
