### ISSUE TITLE
[微信小程序]:选择图片后，裁剪图片未显示

### ISSUE THREAD

**Issue by ioslide** [newbieYoung/Simple-Crop#9]
问题:选择图片后，组件获取的临时图片Type类型为text/plain，裁剪图片未显示
麻烦了！
代码片段:https://developers.weixin.qq.com/s/qvTAYimZ7ngI

![QQ截图20200402115100](https://user-images.githubusercontent.com/41772864/78209000-74d38a80-74d8-11ea-8604-f452dc2fc23f.png)
![QQ截图20200402114920](https://user-images.githubusercontent.com/41772864/78208862-0a224f00-74d8-11ea-94e0-eaf6138c28c8.png)

**Comment by newbieYoung** [comment]
本地开发时，小程序版本太高了不行，我测试 2.9.1 以下是可以的；真机上高版本可以，暂不清楚原因。

**Comment by ioslide** [comment]
> 本地开发时，小程序版本太高了不行，我测试 2.9.1 以下是可以的；真机上高版本可以。

线上正常，感谢

**Comment by newbieYoung** [comment]
不用谢，我的锅，找到原因了，微信小程序高版本 canvasToTempFilePath 必须要要指定 filetype，要不然就默认为 text/plain

**Comment by newbieYoung** [comment]
低版本就没事，我修改下代码，见了微信的鬼了

**Comment by newbieYoung** [comment]
不用谢，见了微信的鬼了

**Comment by newbieYoung** [comment]
该问题主要原因在于 微信小程序 2.9.1 以上版本 canvasToTempFilePath api 中 width、height 没设置值时本地 IDE 中获取默认值异常，导致取不到 dataurl 从而对图片类型判断异常，估计会到 2.11 版本修复。
simplecrop 中已通过显示设置 width、height、destWidth、destHeight 的方式修复了该问题。

**Comment by Kavf** [comment]
> 该问题主要原因在于 微信小程序 2.9.1 以上版本 canvasToTempFilePath api 中 width、height 没设置值时本地 IDE 中获取默认值异常，导致取不到 dataurl 从而对图片类型判断异常，估计会到 2.11 版本修复。
> simplecrop 中已通过显示设置 width、height、destWidth、destHeight 的方式避免了该问题的出现。

小哥哥，我遇到了个问题，裁剪出来的图片特别模糊是怎么回事啊，但是我在那个示例小程序里面裁剪是清晰的。。
